### ISSUE TITLE
Comando: 5etools

### ISSUE THREAD

**Issue by Mallllco** [Steffo99/royalnet#50]
Prendere da https://github.com/TheGiddyLimit/TheGiddyLimit.github.io/tree/master/data tutte le info necessarie e usarle come database per una ricerca di spell, regole, mostri, item e quant'altro.

**Comment by Steffo99** [comment]
Implementata una parte come comando `dnditem`.

**Comment by Steffo99** [comment]
Implementato il comando `dndspell` in 5a59c09

**Comment by Steffo99** [comment]
Altre cose da visualizzare che si potrebbero mettere...?

**Comment by Mallllco** [comment]
Non so, mostri? Opzioni di classe? Regole di base? Non saprei cos'altro al momento
